import type { EditorName } from '../types';

export const EDITORS: { name: EditorName; code: string; color: string; shortCodes: string[] }[] = [
    { name: 'Kiki', code: 'Ki', color: 'bg-purple-100 text-purple-700', shortCodes: ['K', 'Ki'] },
    { name: 'Chloe', code: 'C', color: 'bg-cyan-100 text-cyan-700', shortCodes: ['C', 'D'] }, 
    { name: 'Kathy', code: 'Ka', color: 'bg-rose-100 text-rose-700', shortCodes: ['KH', 'Ka'] },
    { name: 'Kassandra', code: 'Ks', color: 'bg-emerald-100 text-emerald-700', shortCodes: ['Ks'] }, 
    { name: 'Rachel', code: 'Ra', color: 'bg-amber-100 text-amber-700', shortCodes: ['Ra', 'R'] }, 
    { name: 'Loris', code: 'Lo', color: 'bg-orange-100 text-orange-700', shortCodes: ['Lo'] },
];

export const SERIES_RULES = [
  { keywords: ['著數易'], name: '著數易' },
  { keywords: ['健康易'], name: '健康易' },
  { keywords: ['開箱週記'], name: '開箱週記' },
  { keywords: ['街頭巷尾'], name: '街頭巷尾' },
  { keywords: ['玩樂易'], name: '玩樂易' },
  { keywords: ['商場行'], name: '商場行' },
  { keywords: ['那個女生'], name: '那個女生' },
  { keywords: ['圍爐選物'], name: '圍爐選物' },
  { keywords: ['產品實驗室', 'pelabtest', 'pelab test', '產品實測室'], name: '產品實驗室' },
  { keywords: ['玩樂放送'], name: '玩樂放送' },
  { keywords: ['購物攻略'], name: '購物攻略' },
  { keywords: ['食真啲'], name: '食真啲' },
  { keywords: ['一分fact', '1分fact'], name: '一分fact' },
  { keywords: ['搵食指南', '搵食指南'], name: '搵食指南' }, 
  { keywords: ['pebeauty', 'pe beauty'], name: 'PEBeauty' },
  { keywords: ['peculture', 'pe culture'], name: 'PECulture' },
  { keywords: ['pefashion', 'pe fashion'], name: 'PEFashion' },
  { keywords: ['petrend', 'pe trend'], name: 'PETrend' },
  { keywords: ['pe人物故事', 'pe 人物故事'], name: 'PE人物故事' },
  { keywords: ['peers帶路', 'peers 帶路'], name: 'Peers帶路' },
  { keywords: ['peers教路', 'peers 教路'], name: 'Peers教路' },
  { keywords: ['peers訪', 'peers 訪'], name: 'Peers訪' },
  { keywords: ['愛生活'], name: '愛生活' },
  { keywords: ['pecelebrity', 'pe celebrity'], name: 'PECelebrity' },
  { keywords: ['買東買西'], name: '買東買西' },
  { keywords: ['行街尋寶'], name: '行街尋寶' },
  { keywords: ['petutorial', 'pe tutorial'], name: 'PETutorial' },
  { keywords: ['澳門玩食易'], name: '澳門玩食易' },
  { keywords: ['日本玩食易'], name: '日本玩食易' },
  { keywords: ['女生民調'], name: '女生民調' },
  { keywords: ['玩食易攻略'], name: '玩食易攻略' },
  { keywords: ['pe好物不私藏', 'pe 好物不私藏'], name: 'PE好物不私藏' },
  { keywords: ['深圳玩食易'], name: '深圳玩食易' },
  { keywords: ['pehealing', 'pe healing'], name: 'PEHealing' },
  { keywords: ['玩食易限時賞'], name: '玩食易限時賞' },
  { keywords: ['giveaway', '送禮', '抽獎'], name: 'Giveaway' },
  { keywords: ['workshop', '工作坊'], name: 'Workshop' },
];